version: "3"

services:
  db:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped

    environment:
      - MYSQL_DATABASE=todos
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: todo
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - 3001:3000

volumes:
  db:
